# Dependencies
#markdown:            redcarpet
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            turkishmaid
tagline:          'migrationshintergründig.'
description:      'migriert aber hintergrundig.<br>frei aber nicht immer willig.<br>warum fragst du.'
url:              http://turkishmaid.github.io

author:
  name:           'Sara Ziner'
  url:            http://turkishmaid.github.io
  gravatar:       https://en.gravatar.com/turkishmaid
  photo:          http://0.gravatar.com/avatar/f39c629f371c3ac6e89003ecda0a5265?size=100
  introduction:   'migriert aber hintergrundig.<br>frei aber nicht immer willig.<br>warum fragst du.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/lanyon-codinfox.github.io
